algoritmo "Exc02L6"
// 2)
// Ler um vetor com 21 elementos numéricos, e
// apresentar ao usuário os elementos
// em ordem inversa ao da entrada.
var
n: vetor[1..21] de inteiro
x: inteiro

inicio
para x de 1 ate 21 faca
     escreva("Digite um número:  ")
     leia(n[x])
fimpara

escreval


para x de 1 ate 21 faca
       escreval(22- x,"°- ",n[22- x])
fimpara




fimalgoritmo
